apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-gitops-app
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: eks-gitops-app

  template:
    metadata:
      labels:
        app: eks-gitops-app

    spec:
      containers:
        - name: eks-gitops-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
