apiVersion: v1
kind: Service
metadata:
  name: eks-gitops-app
spec:
  type: {{ .Values.service.type }}

  selector:
    app: eks-gitops-app

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
